---
satellite_installer_options: "--foreman-ipa-authentication false --reset-puppet-server-ssl-chain-filepath --disable-system-checks"
satellite_upgrade_options: "--upgrade --disable-system-checks"
verify_rake_task: reimport
db_packages:
  - postgresql-server
  - rh-mongodb34-syspaths
satellite_ansible_version: '2.8'
